package com.lakshmi.mini_project.Model

import java.io.Serializable

data class ResponseDaily(
	val date: Int? = null,
	val state: String? = null,
	val positive: Int? = null,
	val probableCases: Any? = null,
	val negative: Int? = null,
	val pending: Any? = null,
	val totalTestResultsSource: String? = null,
	val totalTestResults: Int? = null,
	val hospitalizedCurrently: Int? = null,
	val hospitalizedCumulative: Any? = null,
	val inIcuCurrently: Int? = null,
	val inIcuCumulative: Any? = null,
	val onVentilatorCurrently: Any? = null,
	val onVentilatorCumulative: Any? = null,
	val recovered: Any? = null,
	val dataQualityGrade: String? = null,
	val lastUpdateEt: String? = null,
	val dateModified: String? = null,
	val checkTimeEt: String? = null,
	val death: Int? = null,
	val hospitalized: Any? = null,
	val dateChecked: String? = null,
	val totalTestsViral: Int? = null,
	val positiveTestsViral: Any? = null,
	val negativeTestsViral: Any? = null,
	val positiveCasesViral: Int? = null,
	val deathConfirmed: Any? = null,
	val deathProbable: Any? = null,
	val totalTestEncountersViral: Any? = null,
	val totalTestsPeopleViral: Any? = null,
	val totalTestsAntibody: Any? = null,
	val positiveTestsAntibody: Any? = null,
	val negativeTestsAntibody: Any? = null,
	val totalTestsPeopleAntibody: Any? = null,
	val positiveTestsPeopleAntibody: Any? = null,
	val negativeTestsPeopleAntibody: Any? = null,
	val totalTestsPeopleAntigen: Any? = null,
	val positiveTestsPeopleAntigen: Any? = null,
	val totalTestsAntigen: Any? = null,
	val positiveTestsAntigen: Any? = null,
	val fips: String? = null,
	val positiveIncrease: Int? = null,
	val negativeIncrease: Int? = null,
	val total: Int? = null,
	val totalTestResultsIncrease: Int? = null,
	val posNeg: Int? = null,
	val deathIncrease: Int? = null,
	val hospitalizedIncrease: Int? = null,
	val hash: String? = null,
	val commercialScore: Int? = null,
	val negativeRegularScore: Int? = null,
	val negativeScore: Int? = null,
	val positiveScore: Int? = null,
	val score: Int? = null,
	val grade: String? = null
)